--------------------------------------------------------
--  File created - Wednesday-January-25-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCESS_GROUPS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."ACCESS_GROUPS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ACCESS_GROUP_METHODS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."ACCESS_GROUP_METHODS" 
   (	"ID" NUMBER, 
	"ACCESS_GROUP_ID" NUMBER, 
	"METHOD_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMINS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."ADMINS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"PASSWORD_HASH" VARCHAR2(100 BYTE), 
	"ACCESS_GROUP_ID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BRANDS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."BRANDS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."CLIENTS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITEMS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."ITEMS" 
   (	"ID" NUMBER, 
	"LABEL" VARCHAR2(255 BYTE), 
	"LOCATION_ID" NUMBER, 
	"BRAND_ID" NUMBER, 
	"SERIAL_NUMBER" VARCHAR2(255 BYTE), 
	"CONDITION_ID" NUMBER, 
	"NOTES" VARCHAR2(255 BYTE), 
	"AVAILABILITY" VARCHAR2(100 BYTE), 
	"TYPE_ID" NUMBER, 
	"DELETED" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITEMSPECVALUES
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."ITEMSPECVALUES" 
   (	"ID" NUMBER, 
	"VALUE" VARCHAR2(50 BYTE), 
	"ITEM_ID" NUMBER, 
	"SPEC_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITEM_CONDITIONS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."ITEM_CONDITIONS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCATIONS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."LOCATIONS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table METHODS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."METHODS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECEIPTS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."RECEIPTS" 
   (	"ID" NUMBER, 
	"CLIENT_ID" NUMBER, 
	"NOTES" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECORDS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."RECORDS" 
   (	"ID" NUMBER, 
	"RETURN_TIME" VARCHAR2(50 BYTE), 
	"RETURN_DATE" VARCHAR2(50 BYTE), 
	"BORROW_TIME" VARCHAR2(50 BYTE), 
	"BORROW_DATE" VARCHAR2(50 BYTE), 
	"ADMIN_CHECKER_ID" NUMBER, 
	"ADMIN_RECEIVER_ID" NUMBER, 
	"CLIENT_BORROWER_ID" NUMBER, 
	"CLIENT_RETURNER_ID" NUMBER, 
	"RECEIPT_ID" NUMBER, 
	"ITEM_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SPECS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."SPECS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"UNIT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SPECS_TYPES
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."SPECS_TYPES" 
   (	"ID" NUMBER, 
	"SPEC_ID" NUMBER, 
	"TYPE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TYPES
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."TYPES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TYPES_TYPES
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."TYPES_TYPES" 
   (	"ID" NUMBER, 
	"TYPE_ID_1" NUMBER, 
	"TYPE_ID_2" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence ACCESS_GROUPS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."ACCESS_GROUPS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ACCESS_GROUP_METHODS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."ACCESS_GROUP_METHODS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ADMINS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."ADMINS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence BRANDS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."BRANDS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence CLIENTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."CLIENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ITEMSPECVALUES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."ITEMSPECVALUES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ITEM_CONDITIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."ITEM_CONDITIONS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence LOCATIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."LOCATIONS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence METHODS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."METHODS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence RECEIPTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."RECEIPTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence RECORDS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."RECORDS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SPECS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."SPECS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SPECS_TYPES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."SPECS_TYPES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence TYPES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."TYPES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence TYPES_TYPES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."TYPES_TYPES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
REM INSERTING into C##ITSTOCK.ACCESS_GROUPS
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.ACCESS_GROUP_METHODS
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.ADMINS
SET DEFINE OFF;
Insert into C##ITSTOCK.ADMINS (ID,NAME,PASSWORD_HASH,ACCESS_GROUP_ID,USERNAME) values (1,'Mohammad Salloum','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',null,'m.salloum');
Insert into C##ITSTOCK.ADMINS (ID,NAME,PASSWORD_HASH,ACCESS_GROUP_ID,USERNAME) values (5,'Maher Saad','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',null,'m.saad');
REM INSERTING into C##ITSTOCK.BRANDS
SET DEFINE OFF;
Insert into C##ITSTOCK.BRANDS (ID,NAME) values (1,'Toshiba');
Insert into C##ITSTOCK.BRANDS (ID,NAME) values (2,'HP');
REM INSERTING into C##ITSTOCK.CLIENTS
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.ITEMS
SET DEFINE OFF;
Insert into C##ITSTOCK.ITEMS (ID,LABEL,LOCATION_ID,BRAND_ID,SERIAL_NUMBER,CONDITION_ID,NOTES,AVAILABILITY,TYPE_ID,DELETED) values (2,'USB 1',2,2,'5678',2,null,'0',2,0);
Insert into C##ITSTOCK.ITEMS (ID,LABEL,LOCATION_ID,BRAND_ID,SERIAL_NUMBER,CONDITION_ID,NOTES,AVAILABILITY,TYPE_ID,DELETED) values (3,'IT SUPPORT 2',2,2,'987',3,null,'1',1,0);
Insert into C##ITSTOCK.ITEMS (ID,LABEL,LOCATION_ID,BRAND_ID,SERIAL_NUMBER,CONDITION_ID,NOTES,AVAILABILITY,TYPE_ID,DELETED) values (4,'IT SUPPORT 3',1,1,'2032',4,null,'1',1,0);
Insert into C##ITSTOCK.ITEMS (ID,LABEL,LOCATION_ID,BRAND_ID,SERIAL_NUMBER,CONDITION_ID,NOTES,AVAILABILITY,TYPE_ID,DELETED) values (5,'IT SUPPORT 4',1,2,'99VZS13',5,null,'0',1,0);
Insert into C##ITSTOCK.ITEMS (ID,LABEL,LOCATION_ID,BRAND_ID,SERIAL_NUMBER,CONDITION_ID,NOTES,AVAILABILITY,TYPE_ID,DELETED) values (1,'IT SUPPORT 1',1,1,'1234',1,null,'1',1,0);
REM INSERTING into C##ITSTOCK.ITEMSPECVALUES
SET DEFINE OFF;
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (4,'6',3,1);
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (5,'2',3,2);
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (6,'15',3,3);
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (7,'16',4,1);
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (8,'4',3,2);
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (9,'19',3,3);
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (10,'2',4,1);
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (11,'1',4,2);
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (23,'14',4,3);
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (13,'8',5,1);
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (14,'3',5,2);
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (15,'27',5,3);
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (16,'32',2,4);
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (1,'4',1,1);
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (2,'3.2',1,2);
Insert into C##ITSTOCK.ITEMSPECVALUES (ID,VALUE,ITEM_ID,SPEC_ID) values (3,'17',1,3);
REM INSERTING into C##ITSTOCK.ITEM_CONDITIONS
SET DEFINE OFF;
Insert into C##ITSTOCK.ITEM_CONDITIONS (ID,NAME) values (5,'Bad');
Insert into C##ITSTOCK.ITEM_CONDITIONS (ID,NAME) values (1,'Brand New');
Insert into C##ITSTOCK.ITEM_CONDITIONS (ID,NAME) values (2,'Excellent');
Insert into C##ITSTOCK.ITEM_CONDITIONS (ID,NAME) values (4,'Good');
Insert into C##ITSTOCK.ITEM_CONDITIONS (ID,NAME) values (7,'Total Waste');
Insert into C##ITSTOCK.ITEM_CONDITIONS (ID,NAME) values (6,'Very Bad');
Insert into C##ITSTOCK.ITEM_CONDITIONS (ID,NAME) values (3,'Very Good');
REM INSERTING into C##ITSTOCK.LOCATIONS
SET DEFINE OFF;
Insert into C##ITSTOCK.LOCATIONS (ID,NAME) values (1,'Warehouse');
Insert into C##ITSTOCK.LOCATIONS (ID,NAME) values (2,'Closet 1');
REM INSERTING into C##ITSTOCK.METHODS
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.RECEIPTS
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.RECORDS
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.SPECS
SET DEFINE OFF;
Insert into C##ITSTOCK.SPECS (ID,NAME,UNIT) values (1,'RAM','GB');
Insert into C##ITSTOCK.SPECS (ID,NAME,UNIT) values (2,'CPU','GHz');
Insert into C##ITSTOCK.SPECS (ID,NAME,UNIT) values (3,'Screen',null);
Insert into C##ITSTOCK.SPECS (ID,NAME,UNIT) values (4,'Capacity','GB');
REM INSERTING into C##ITSTOCK.SPECS_TYPES
SET DEFINE OFF;
Insert into C##ITSTOCK.SPECS_TYPES (ID,SPEC_ID,TYPE_ID) values (1,1,1);
Insert into C##ITSTOCK.SPECS_TYPES (ID,SPEC_ID,TYPE_ID) values (2,2,1);
Insert into C##ITSTOCK.SPECS_TYPES (ID,SPEC_ID,TYPE_ID) values (3,3,1);
Insert into C##ITSTOCK.SPECS_TYPES (ID,SPEC_ID,TYPE_ID) values (4,4,2);
REM INSERTING into C##ITSTOCK.TYPES
SET DEFINE OFF;
Insert into C##ITSTOCK.TYPES (ID,NAME) values (1,'Laptop');
Insert into C##ITSTOCK.TYPES (ID,NAME) values (2,'USB');
REM INSERTING into C##ITSTOCK.TYPES_TYPES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index METHODS_NAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."METHODS_NAME_UNIQUE" ON "C##ITSTOCK"."METHODS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."NAME_UNIQUE" ON "C##ITSTOCK"."ITEM_CONDITIONS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SPECS_TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."SPECS_TYPES_PK" ON "C##ITSTOCK"."SPECS_TYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOCATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."LOCATIONS_PK" ON "C##ITSTOCK"."LOCATIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ACCESS_GROUPS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."ACCESS_GROUPS_PK" ON "C##ITSTOCK"."ACCESS_GROUPS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."ITEMS_PK" ON "C##ITSTOCK"."ITEMS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTS_NAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."CLIENTS_NAME_UNIQUE" ON "C##ITSTOCK"."CLIENTS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ITEMSPECVALUES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."ITEMSPECVALUES_PK" ON "C##ITSTOCK"."ITEMSPECVALUES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TYPES_TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."TYPES_TYPES_PK" ON "C##ITSTOCK"."TYPES_TYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TYPES_NAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."TYPES_NAME_UNIQUE" ON "C##ITSTOCK"."TYPES" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index METHODS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."METHODS_PK" ON "C##ITSTOCK"."METHODS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."TABLE2_PK" ON "C##ITSTOCK"."RECORDS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ACCESS_GROUP_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."ACCESS_GROUP_NAME" ON "C##ITSTOCK"."ACCESS_GROUPS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RECEIPTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."RECEIPTS_PK" ON "C##ITSTOCK"."RECEIPTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SPECS_NAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."SPECS_NAME_UNIQUE" ON "C##ITSTOCK"."SPECS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_ADMINS_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."UNIQUE_ADMINS_NAME" ON "C##ITSTOCK"."ADMINS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ITEM_CONDITIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."ITEM_CONDITIONS_PK" ON "C##ITSTOCK"."ITEM_CONDITIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BRANDS_NAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."BRANDS_NAME_UNIQUE" ON "C##ITSTOCK"."BRANDS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."TYPES_PK" ON "C##ITSTOCK"."TYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."TABLE1_PK" ON "C##ITSTOCK"."ADMINS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BRANDS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."BRANDS_PK" ON "C##ITSTOCK"."BRANDS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."CLIENTS_PK" ON "C##ITSTOCK"."CLIENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SPECS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."SPECS_PK" ON "C##ITSTOCK"."SPECS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOCATIONS_NAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."LOCATIONS_NAME_UNIQUE" ON "C##ITSTOCK"."LOCATIONS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ACCESS_GROUP_METHODS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."ACCESS_GROUP_METHODS_PK" ON "C##ITSTOCK"."ACCESS_GROUP_METHODS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ACCESS_GROUPS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."ACCESS_GROUPS_TRG" 
BEFORE INSERT ON ACCESS_GROUPS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ACCESS_GROUPS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."ACCESS_GROUPS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACCESS_GROUP_METHODS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."ACCESS_GROUP_METHODS_TRG" 
BEFORE INSERT ON ACCESS_GROUP_METHODS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ACCESS_GROUP_METHODS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."ACCESS_GROUP_METHODS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ADMINS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."ADMINS_TRG" 
BEFORE INSERT ON ADMINS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ADMINS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."ADMINS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BRANDS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."BRANDS_TRG" 
BEFORE INSERT ON BRANDS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT BRANDS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."BRANDS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLIENTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."CLIENTS_TRG" 
BEFORE INSERT ON CLIENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CLIENTS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."CLIENTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ITEMSPECVALUES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."ITEMSPECVALUES_TRG" 
BEFORE INSERT ON ITEMSPECVALUES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ITEMSPECVALUES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."ITEMSPECVALUES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ITEMS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."ITEMS_TRG" 
BEFORE INSERT ON ITEMS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."ITEMS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ITEM_CONDITIONS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."ITEM_CONDITIONS_TRG" 
BEFORE INSERT ON ITEM_CONDITIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ITEM_CONDITIONS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."ITEM_CONDITIONS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOCATIONS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."LOCATIONS_TRG" 
BEFORE INSERT ON LOCATIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT LOCATIONS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."LOCATIONS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger METHODS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."METHODS_TRG" 
BEFORE INSERT ON METHODS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT METHODS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."METHODS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECEIPTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."RECEIPTS_TRG" 
BEFORE INSERT ON RECEIPTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT RECEIPTS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."RECEIPTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECORDS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."RECORDS_TRG" 
BEFORE INSERT ON RECORDS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT RECORDS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."RECORDS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SPECS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."SPECS_TRG" 
BEFORE INSERT ON SPECS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SPECS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."SPECS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SPECS_TYPES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."SPECS_TYPES_TRG" 
BEFORE INSERT ON SPECS_TYPES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SPECS_TYPES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."SPECS_TYPES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TYPES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."TYPES_TRG" 
BEFORE INSERT ON TYPES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TYPES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."TYPES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TYPES_TYPES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."TYPES_TYPES_TRG" 
BEFORE INSERT ON TYPES_TYPES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TYPES_TYPES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."TYPES_TYPES_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMINS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ADMINS" ADD CONSTRAINT "UNIQUE_ADMINS_NAME" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ADMINS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ADMINS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCATIONS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."LOCATIONS" ADD CONSTRAINT "LOCATIONS_NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."LOCATIONS" ADD CONSTRAINT "LOCATIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."LOCATIONS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCESS_GROUPS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ACCESS_GROUPS" ADD CONSTRAINT "ACCESS_GROUP_NAME" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ACCESS_GROUPS" ADD CONSTRAINT "ACCESS_GROUPS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ACCESS_GROUPS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECEIPTS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."RECEIPTS" ADD CONSTRAINT "RECEIPTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."RECEIPTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ITEM_CONDITIONS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ITEM_CONDITIONS" ADD CONSTRAINT "NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ITEM_CONDITIONS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ITSTOCK"."ITEM_CONDITIONS" ADD CONSTRAINT "ITEM_CONDITIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ITEM_CONDITIONS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."CLIENTS" ADD CONSTRAINT "CLIENTS_NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."CLIENTS" ADD CONSTRAINT "CLIENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."CLIENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TYPES
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."TYPES" ADD CONSTRAINT "TYPES_NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."TYPES" ADD CONSTRAINT "TYPES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."TYPES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPECS_TYPES
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."SPECS_TYPES" ADD CONSTRAINT "SPECS_TYPES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."SPECS_TYPES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BRANDS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."BRANDS" ADD CONSTRAINT "BRANDS_NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."BRANDS" ADD CONSTRAINT "BRANDS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."BRANDS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ITEMSPECVALUES
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ITEMSPECVALUES" ADD CONSTRAINT "ITEMSPECVALUES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ITEMSPECVALUES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECORDS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."RECORDS" ADD CONSTRAINT "TABLE2_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."RECORDS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ITEMS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ITEMS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "C##ITSTOCK"."ITEMS" ADD CONSTRAINT "ITEMS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ITEMS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table METHODS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."METHODS" ADD CONSTRAINT "METHODS_NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."METHODS" ADD CONSTRAINT "METHODS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."METHODS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCESS_GROUP_METHODS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ACCESS_GROUP_METHODS" ADD CONSTRAINT "ACCESS_GROUP_METHODS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ACCESS_GROUP_METHODS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPECS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."SPECS" ADD CONSTRAINT "SPECS_NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."SPECS" ADD CONSTRAINT "SPECS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."SPECS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TYPES_TYPES
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."TYPES_TYPES" ADD CONSTRAINT "TYPES_TYPES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."TYPES_TYPES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACCESS_GROUP_METHODS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ACCESS_GROUP_METHODS" ADD CONSTRAINT "ACCESS_GROUP_FK" FOREIGN KEY ("ACCESS_GROUP_ID")
	  REFERENCES "C##ITSTOCK"."ACCESS_GROUPS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."ACCESS_GROUP_METHODS" ADD CONSTRAINT "METHOD_FK" FOREIGN KEY ("METHOD_ID")
	  REFERENCES "C##ITSTOCK"."METHODS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADMINS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ADMINS" ADD CONSTRAINT "USER_ACCESS_GROUP_FK" FOREIGN KEY ("ACCESS_GROUP_ID")
	  REFERENCES "C##ITSTOCK"."ACCESS_GROUPS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ITEMS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ITEMS" ADD CONSTRAINT "ITEM_BRAND_FK" FOREIGN KEY ("BRAND_ID")
	  REFERENCES "C##ITSTOCK"."BRANDS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."ITEMS" ADD CONSTRAINT "ITEM_LOCATION_FK" FOREIGN KEY ("LOCATION_ID")
	  REFERENCES "C##ITSTOCK"."LOCATIONS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."ITEMS" ADD CONSTRAINT "ITEM_TYPE_FK" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "C##ITSTOCK"."TYPES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ITEMSPECVALUES
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ITEMSPECVALUES" ADD CONSTRAINT "ITEMSPECVALUE_ITEM_FK" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "C##ITSTOCK"."ITEMS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."ITEMSPECVALUES" ADD CONSTRAINT "ITEMSPECVALUE_SPEC_FK" FOREIGN KEY ("SPEC_ID")
	  REFERENCES "C##ITSTOCK"."SPECS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECEIPTS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."RECEIPTS" ADD CONSTRAINT "RECEIPT_CLIENT_FK" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "C##ITSTOCK"."CLIENTS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECORDS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."RECORDS" ADD CONSTRAINT "RECORD_BORROWER_FK" FOREIGN KEY ("CLIENT_BORROWER_ID")
	  REFERENCES "C##ITSTOCK"."CLIENTS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."RECORDS" ADD CONSTRAINT "RECORD_CHECKER_FK" FOREIGN KEY ("ADMIN_CHECKER_ID")
	  REFERENCES "C##ITSTOCK"."ADMINS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."RECORDS" ADD CONSTRAINT "RECORD_ITEM_FK" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "C##ITSTOCK"."ITEMS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."RECORDS" ADD CONSTRAINT "RECORD_RECEIPT_FK" FOREIGN KEY ("RECEIPT_ID")
	  REFERENCES "C##ITSTOCK"."RECEIPTS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."RECORDS" ADD CONSTRAINT "RECORD_RECEIVER_FK" FOREIGN KEY ("ADMIN_RECEIVER_ID")
	  REFERENCES "C##ITSTOCK"."ADMINS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."RECORDS" ADD CONSTRAINT "RECORD_RETURNER_FK" FOREIGN KEY ("CLIENT_RETURNER_ID")
	  REFERENCES "C##ITSTOCK"."CLIENTS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPECS_TYPES
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."SPECS_TYPES" ADD CONSTRAINT "SPEC_FK" FOREIGN KEY ("SPEC_ID")
	  REFERENCES "C##ITSTOCK"."SPECS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."SPECS_TYPES" ADD CONSTRAINT "TYPE_FK" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "C##ITSTOCK"."TYPES" ("ID") ENABLE;
