--------------------------------------------------------
--  File created - Saturday-March-11-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCESS_GROUPS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."ACCESS_GROUPS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ACCESS_GROUPS_METHODS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."ACCESS_GROUPS_METHODS" 
   (	"ID" NUMBER, 
	"ACCESS_GROUP_ID" NUMBER, 
	"METHOD_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMINS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."ADMINS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"PASSWORD_HASH" VARCHAR2(100 BYTE), 
	"ACCESS_GROUP_ID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"NOTIFICATION" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BRANDS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."BRANDS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."CLIENTS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITEMS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."ITEMS" 
   (	"ID" NUMBER, 
	"LABEL" VARCHAR2(255 BYTE), 
	"LOCATION_ID" NUMBER DEFAULT 3, 
	"BRAND_ID" NUMBER DEFAULT 3, 
	"SERIAL_NUMBER" VARCHAR2(255 BYTE), 
	"CONDITION_ID" NUMBER, 
	"NOTES" VARCHAR2(255 BYTE) DEFAULT 1, 
	"AVAILABILITY" VARCHAR2(100 BYTE) DEFAULT 1, 
	"TYPE_ID" NUMBER, 
	"DELETED" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITEMSPECVALUES
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."ITEMSPECVALUES" 
   (	"ID" NUMBER, 
	"VALUE" VARCHAR2(50 BYTE), 
	"ITEM_ID" NUMBER, 
	"SPEC_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITEM_CONDITIONS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."ITEM_CONDITIONS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCATIONS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."LOCATIONS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table METHODS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."METHODS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECEIPTS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."RECEIPTS" 
   (	"ID" NUMBER, 
	"CLIENT_ID" NUMBER, 
	"NOTES" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"COUNTRY" VARCHAR2(50 BYTE), 
	"RECEIVER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECORDS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."RECORDS" 
   (	"ID" NUMBER, 
	"RETURN_DATETIME" TIMESTAMP (6), 
	"BORROW_DATETIME" TIMESTAMP (6), 
	"ADMIN_CHECKER_ID" NUMBER, 
	"ADMIN_RECEIVER_ID" NUMBER, 
	"CLIENT_BORROWER_ID" NUMBER, 
	"CLIENT_RETURNER_ID" NUMBER, 
	"RECEIPT_ID" NUMBER, 
	"ITEM_ID" NUMBER, 
	"DELETED" VARCHAR2(50 BYTE) DEFAULT 0, 
	"EXPECTED_DATE" DATE, 
	"NOTES" VARCHAR2(50 BYTE), 
	"RETURNING" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SPECS
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."SPECS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"UNIT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SPECS_TYPES
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."SPECS_TYPES" 
   (	"ID" NUMBER, 
	"SPEC_ID" NUMBER, 
	"TYPE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TYPES
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."TYPES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TYPES_TYPES
--------------------------------------------------------

  CREATE TABLE "C##ITSTOCK"."TYPES_TYPES" 
   (	"ID" NUMBER, 
	"TYPE_ID_1" NUMBER, 
	"TYPE_ID_2" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence ACCESS_GROUPS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."ACCESS_GROUPS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ACCESS_GROUP_METHODS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."ACCESS_GROUP_METHODS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 601 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ADMINS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."ADMINS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence BRANDS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."BRANDS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence CLIENTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."CLIENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ITEMSPECVALUES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."ITEMSPECVALUES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 281 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ITEMS_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."ITEMS_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ITEM_CONDITIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."ITEM_CONDITIONS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence LOCATIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."LOCATIONS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence METHODS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."METHODS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence RECEIPTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."RECEIPTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence RECEIPTS_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."RECEIPTS_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence RECEIPTS_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."RECEIPTS_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence RECEIPTS_SEQ3
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."RECEIPTS_SEQ3"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence RECORDS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."RECORDS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence RECORDS_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."RECORDS_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence RECORDS_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."RECORDS_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 321 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SPECS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."SPECS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SPECS_TYPES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."SPECS_TYPES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence TYPES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."TYPES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence TYPES_TYPES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITSTOCK"."TYPES_TYPES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
REM INSERTING into C##ITSTOCK.ACCESS_GROUPS
SET DEFINE OFF;
Insert into C##ITSTOCK.ACCESS_GROUPS (ID,NAME) values (1,'super');
Insert into C##ITSTOCK.ACCESS_GROUPS (ID,NAME) values (2,'admin');
Insert into C##ITSTOCK.ACCESS_GROUPS (ID,NAME) values (3,'it');
Insert into C##ITSTOCK.ACCESS_GROUPS (ID,NAME) values (4,'guest');
REM INSERTING into C##ITSTOCK.ACCESS_GROUPS_METHODS
SET DEFINE OFF;
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (580,3,48);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (582,3,19);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (551,1,47);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (553,1,48);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (555,1,19);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (557,1,43);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (559,1,23);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (576,3,21);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (578,3,47);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (62,null,19);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (554,1,6);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (556,1,42);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (558,1,26);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (550,1,46);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (552,1,49);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (539,1,45);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (541,1,29);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (543,1,25);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (545,1,3);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (547,1,28);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (549,1,22);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (560,2,21);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (561,2,29);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (562,2,44);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (563,2,25);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (564,2,27);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (565,2,3);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (566,2,41);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (567,2,28);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (569,2,49);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (570,2,48);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (571,2,6);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (572,2,19);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (573,2,42);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (574,2,43);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (575,2,26);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (544,1,27);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (540,1,21);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (542,1,44);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (546,1,41);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (548,1,24);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (568,2,47);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (579,3,49);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (581,3,6);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (583,3,26);
Insert into C##ITSTOCK.ACCESS_GROUPS_METHODS (ID,ACCESS_GROUP_ID,METHOD_ID) values (577,3,25);
REM INSERTING into C##ITSTOCK.ADMINS
SET DEFINE OFF;
Insert into C##ITSTOCK.ADMINS (ID,NAME,PASSWORD_HASH,ACCESS_GROUP_ID,USERNAME,EMAIL,NOTIFICATION) values (84,'Maher Saad','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',2,'ma.saad','ma.saad@almayadeen.net','NO');
Insert into C##ITSTOCK.ADMINS (ID,NAME,PASSWORD_HASH,ACCESS_GROUP_ID,USERNAME,EMAIL,NOTIFICATION) values (44,'Jaafar Krayem','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',2,'j.krayem','j.krayem@almayadeen.net','NO');
Insert into C##ITSTOCK.ADMINS (ID,NAME,PASSWORD_HASH,ACCESS_GROUP_ID,USERNAME,EMAIL,NOTIFICATION) values (45,'Wassim El Ahmar','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',1,'w.elahmar','w.elahmar@almayadeen.net','NO');
Insert into C##ITSTOCK.ADMINS (ID,NAME,PASSWORD_HASH,ACCESS_GROUP_ID,USERNAME,EMAIL,NOTIFICATION) values (63,'Ahmad Hammoud','9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',2,'a.hammoud','a.hammoud@almayadeen.net','NO');
Insert into C##ITSTOCK.ADMINS (ID,NAME,PASSWORD_HASH,ACCESS_GROUP_ID,USERNAME,EMAIL,NOTIFICATION) values (61,'Mohammad Awwad','c7e616822f366fb1b5e0756af498cc11d2c0862edcb32ca65882f622ff39de1b',4,'m.awwad','m.awad@almayadeen.net','NO');
Insert into C##ITSTOCK.ADMINS (ID,NAME,PASSWORD_HASH,ACCESS_GROUP_ID,USERNAME,EMAIL,NOTIFICATION) values (65,'Farid Assi','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',4,'f.assi','f.assi@almayadeen.net','NO');
Insert into C##ITSTOCK.ADMINS (ID,NAME,PASSWORD_HASH,ACCESS_GROUP_ID,USERNAME,EMAIL,NOTIFICATION) values (82,'Saeed Souwaidan','34c3b34443b279a3145e562dcc1623d2c5253480c4fa1080449bd8284b6fdcf8',2,'s.souwaidan','s.souwaidan@almayadeen.net','NO');
Insert into C##ITSTOCK.ADMINS (ID,NAME,PASSWORD_HASH,ACCESS_GROUP_ID,USERNAME,EMAIL,NOTIFICATION) values (67,'Roy Dagher','b03ddf3ca2e714a6548e7495e2a03f5e824eaac9837cd7f159c67b90fb4b7342',2,'roy','r.dagher@almayadeen.net','NO');
Insert into C##ITSTOCK.ADMINS (ID,NAME,PASSWORD_HASH,ACCESS_GROUP_ID,USERNAME,EMAIL,NOTIFICATION) values (1,'Mohammad Salloum','6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b',1,'m.salloum','m.salloum@almayadeen.net','TO');
Insert into C##ITSTOCK.ADMINS (ID,NAME,PASSWORD_HASH,ACCESS_GROUP_ID,USERNAME,EMAIL,NOTIFICATION) values (66,'Jalal Shaer','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',4,'j.shaer','j.shaer@almayadeen.net','NO');
Insert into C##ITSTOCK.ADMINS (ID,NAME,PASSWORD_HASH,ACCESS_GROUP_ID,USERNAME,EMAIL,NOTIFICATION) values (83,'Hadi Halawi','481f6cc0511143ccdd7e2d1b1b94faf0a700a8b49cd13922a70b5ae28acaa8c5',2,'h.halawi','h.halawi@almayadeen.net','NO');
Insert into C##ITSTOCK.ADMINS (ID,NAME,PASSWORD_HASH,ACCESS_GROUP_ID,USERNAME,EMAIL,NOTIFICATION) values (64,'Ismail Omar','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',4,'i.omar','i.omar@almayadeen.net','NO');
REM INSERTING into C##ITSTOCK.BRANDS
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.CLIENTS
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.ITEMS
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.ITEMSPECVALUES
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.ITEM_CONDITIONS
SET DEFINE OFF;
Insert into C##ITSTOCK.ITEM_CONDITIONS (ID,NAME) values (5,'Bad');
Insert into C##ITSTOCK.ITEM_CONDITIONS (ID,NAME) values (1,'Brand New');
Insert into C##ITSTOCK.ITEM_CONDITIONS (ID,NAME) values (2,'Excellent');
Insert into C##ITSTOCK.ITEM_CONDITIONS (ID,NAME) values (4,'Good');
Insert into C##ITSTOCK.ITEM_CONDITIONS (ID,NAME) values (7,'Total Waste');
Insert into C##ITSTOCK.ITEM_CONDITIONS (ID,NAME) values (6,'Very Bad');
Insert into C##ITSTOCK.ITEM_CONDITIONS (ID,NAME) values (3,'Very Good');
REM INSERTING into C##ITSTOCK.LOCATIONS
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.METHODS
SET DEFINE OFF;
Insert into C##ITSTOCK.METHODS (ID,NAME) values (25,'checkout_item');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (41,'delete_spec');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (22,'manage_access');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (6,'search_items');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (27,'delete_item');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (42,'update_spec_name');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (45,'add_access_group');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (19,'search_records');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (21,'add_item');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (3,'delete_record');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (24,'edit_receipt');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (44,'add_spec_to_type');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (46,'reset_password');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (47,'return_item');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (48,'return_record');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (28,'edit_item');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (43,'update_type_name');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (49,'return_receipt');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (29,'add_new_specs_to_item');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (23,'view_logs');
Insert into C##ITSTOCK.METHODS (ID,NAME) values (26,'view_items_hq');
REM INSERTING into C##ITSTOCK.RECEIPTS
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.RECORDS
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.SPECS
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.SPECS_TYPES
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.TYPES
SET DEFINE OFF;
REM INSERTING into C##ITSTOCK.TYPES_TYPES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index METHODS_NAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."METHODS_NAME_UNIQUE" ON "C##ITSTOCK"."METHODS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."NAME_UNIQUE" ON "C##ITSTOCK"."ITEM_CONDITIONS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SPECS_TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."SPECS_TYPES_PK" ON "C##ITSTOCK"."SPECS_TYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOCATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."LOCATIONS_PK" ON "C##ITSTOCK"."LOCATIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ACCESS_GROUPS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."ACCESS_GROUPS_PK" ON "C##ITSTOCK"."ACCESS_GROUPS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ITEMS_LABEL_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."ITEMS_LABEL_UNIQUE" ON "C##ITSTOCK"."ITEMS" ("LABEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."ITEMS_PK" ON "C##ITSTOCK"."ITEMS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTS_NAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."CLIENTS_NAME_UNIQUE" ON "C##ITSTOCK"."CLIENTS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ITEMSPECVALUES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."ITEMSPECVALUES_PK" ON "C##ITSTOCK"."ITEMSPECVALUES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TYPES_TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."TYPES_TYPES_PK" ON "C##ITSTOCK"."TYPES_TYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TYPES_NAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."TYPES_NAME_UNIQUE" ON "C##ITSTOCK"."TYPES" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index METHODS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."METHODS_PK" ON "C##ITSTOCK"."METHODS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."TABLE2_PK" ON "C##ITSTOCK"."RECORDS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ACCESS_GROUP_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."ACCESS_GROUP_NAME" ON "C##ITSTOCK"."ACCESS_GROUPS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RECEIPTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."RECEIPTS_PK" ON "C##ITSTOCK"."RECEIPTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SPECS_NAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."SPECS_NAME_UNIQUE" ON "C##ITSTOCK"."SPECS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_ADMINS_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."UNIQUE_ADMINS_NAME" ON "C##ITSTOCK"."ADMINS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ITEM_CONDITIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."ITEM_CONDITIONS_PK" ON "C##ITSTOCK"."ITEM_CONDITIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BRANDS_NAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."BRANDS_NAME_UNIQUE" ON "C##ITSTOCK"."BRANDS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."TYPES_PK" ON "C##ITSTOCK"."TYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."TABLE1_PK" ON "C##ITSTOCK"."ADMINS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BRANDS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."BRANDS_PK" ON "C##ITSTOCK"."BRANDS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."CLIENTS_PK" ON "C##ITSTOCK"."CLIENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SPECS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."SPECS_PK" ON "C##ITSTOCK"."SPECS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOCATIONS_NAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."LOCATIONS_NAME_UNIQUE" ON "C##ITSTOCK"."LOCATIONS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ACCESS_GROUP_METHODS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITSTOCK"."ACCESS_GROUP_METHODS_PK" ON "C##ITSTOCK"."ACCESS_GROUPS_METHODS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ACCESS_GROUPS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."ACCESS_GROUPS_TRG" 
BEFORE INSERT ON ACCESS_GROUPS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ACCESS_GROUPS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."ACCESS_GROUPS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACCESS_GROUP_METHODS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."ACCESS_GROUP_METHODS_TRG" 
BEFORE INSERT ON "ACCESS_GROUPS_METHODS" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ACCESS_GROUP_METHODS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."ACCESS_GROUP_METHODS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ADMINS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."ADMINS_TRG" 
BEFORE INSERT ON ADMINS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ADMINS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."ADMINS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BRANDS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."BRANDS_TRG" 
BEFORE INSERT ON BRANDS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT BRANDS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."BRANDS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLIENTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."CLIENTS_TRG" 
BEFORE INSERT ON CLIENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CLIENTS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."CLIENTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ITEMSPECVALUES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."ITEMSPECVALUES_TRG" 
BEFORE INSERT ON ITEMSPECVALUES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ITEMSPECVALUES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."ITEMSPECVALUES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ITEMS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."ITEMS_TRG" 
BEFORE INSERT ON ITEMS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ITEMS_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."ITEMS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ITEMS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."ITEMS_TRG1" 
BEFORE INSERT ON ITEMS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."ITEMS_TRG1" DISABLE;
--------------------------------------------------------
--  DDL for Trigger ITEM_CONDITIONS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."ITEM_CONDITIONS_TRG" 
BEFORE INSERT ON ITEM_CONDITIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ITEM_CONDITIONS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."ITEM_CONDITIONS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOCATIONS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."LOCATIONS_TRG" 
BEFORE INSERT ON LOCATIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT LOCATIONS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."LOCATIONS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger METHODS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."METHODS_TRG" 
BEFORE INSERT ON METHODS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT METHODS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."METHODS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECEIPTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."RECEIPTS_TRG" 
BEFORE INSERT ON RECEIPTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."RECEIPTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECEIPTS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."RECEIPTS_TRG1" 
BEFORE INSERT ON RECEIPTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."RECEIPTS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECEIPTS_TRG2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."RECEIPTS_TRG2" 
BEFORE INSERT ON RECEIPTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."RECEIPTS_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECEIPTS_TRG3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."RECEIPTS_TRG3" 
BEFORE INSERT ON RECEIPTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT RECEIPTS_SEQ3.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."RECEIPTS_TRG3" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECORDS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."RECORDS_TRG" 
BEFORE INSERT ON RECORDS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."RECORDS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECORDS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."RECORDS_TRG1" 
BEFORE INSERT ON RECORDS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."RECORDS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECORDS_TRG2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."RECORDS_TRG2" 
BEFORE INSERT ON RECORDS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT RECORDS_SEQ2.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."RECORDS_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SPECS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."SPECS_TRG" 
BEFORE INSERT ON SPECS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SPECS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."SPECS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SPECS_TYPES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."SPECS_TYPES_TRG" 
BEFORE INSERT ON SPECS_TYPES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SPECS_TYPES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."SPECS_TYPES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_ITEM_AVAILABILITY_OUT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."TRIGGER_ITEM_AVAILABILITY_OUT" 
AFTER INSERT ON RECORDS 
FOR EACH ROW
BEGIN
  UPDATE ITEMS SET AVAILABILITY = 0 WHERE ID = :NEW.ITEM_ID;
END;
/
ALTER TRIGGER "C##ITSTOCK"."TRIGGER_ITEM_AVAILABILITY_OUT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_ITEM_DELETE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."TRIGGER_ITEM_DELETE" 
BEFORE UPDATE 
  OF DELETED
  ON ITEMS
  FOR EACH ROW

BEGIN
IF :NEW.DELETED = '1' THEN
  DELETE FROM ITEMSPECVALUES WHERE ITEM_ID = :OLD.ID;
  UPDATE RECORDS SET DELETED = 1 WHERE ITEM_ID = :OLD.ID; 
  :NEW.LABEL := '!$#' || :OLD.LABEL || '!$#' || :OLD.ID;
  :NEW.SERIAL_NUMBER := '!$#' || :OLD.SERIAL_NUMBER || '!$#' || :OLD.ID;
END IF;
END;
/
ALTER TRIGGER "C##ITSTOCK"."TRIGGER_ITEM_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TYPES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."TYPES_TRG" 
BEFORE INSERT ON TYPES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TYPES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."TYPES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TYPES_TYPES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITSTOCK"."TYPES_TYPES_TRG" 
BEFORE INSERT ON TYPES_TYPES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TYPES_TYPES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITSTOCK"."TYPES_TYPES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Procedure DELETE_SPEC
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##ITSTOCK"."DELETE_SPEC" AS 
BEGIN
  
  NULL;
END DELETE_SPEC;

/
--------------------------------------------------------
--  Constraints for Table ADMINS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ADMINS" ADD CONSTRAINT "UNIQUE_ADMINS_NAME" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ADMINS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ADMINS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCATIONS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."LOCATIONS" ADD CONSTRAINT "LOCATIONS_NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."LOCATIONS" ADD CONSTRAINT "LOCATIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."LOCATIONS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCESS_GROUPS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ACCESS_GROUPS" ADD CONSTRAINT "ACCESS_GROUP_NAME" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ACCESS_GROUPS" ADD CONSTRAINT "ACCESS_GROUPS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ACCESS_GROUPS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECEIPTS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."RECEIPTS" ADD CONSTRAINT "RECEIPTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."RECEIPTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ITEM_CONDITIONS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ITEM_CONDITIONS" ADD CONSTRAINT "NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ITEM_CONDITIONS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ITSTOCK"."ITEM_CONDITIONS" ADD CONSTRAINT "ITEM_CONDITIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ITEM_CONDITIONS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."CLIENTS" ADD CONSTRAINT "CLIENTS_NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."CLIENTS" ADD CONSTRAINT "CLIENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."CLIENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TYPES
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."TYPES" ADD CONSTRAINT "TYPES_NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."TYPES" ADD CONSTRAINT "TYPES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."TYPES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPECS_TYPES
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."SPECS_TYPES" ADD CONSTRAINT "SPECS_TYPES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."SPECS_TYPES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BRANDS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."BRANDS" ADD CONSTRAINT "BRANDS_NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."BRANDS" ADD CONSTRAINT "BRANDS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."BRANDS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ITEMSPECVALUES
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ITEMSPECVALUES" MODIFY ("SPEC_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ITSTOCK"."ITEMSPECVALUES" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ITSTOCK"."ITEMSPECVALUES" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "C##ITSTOCK"."ITEMSPECVALUES" ADD CONSTRAINT "ITEMSPECVALUES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ITEMSPECVALUES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECORDS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."RECORDS" MODIFY ("RETURNING" NOT NULL ENABLE);
  ALTER TABLE "C##ITSTOCK"."RECORDS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "C##ITSTOCK"."RECORDS" ADD CONSTRAINT "TABLE2_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."RECORDS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCESS_GROUPS_METHODS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ACCESS_GROUPS_METHODS" ADD CONSTRAINT "ACCESS_GROUP_METHODS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ACCESS_GROUPS_METHODS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ITEMS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ITEMS" ADD CONSTRAINT "ITEMS_LABEL_UNIQUE" UNIQUE ("LABEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ITEMS" MODIFY ("TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ITSTOCK"."ITEMS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "C##ITSTOCK"."ITEMS" ADD CONSTRAINT "ITEMS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."ITEMS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table METHODS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."METHODS" ADD CONSTRAINT "METHODS_NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."METHODS" ADD CONSTRAINT "METHODS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."METHODS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPECS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."SPECS" ADD CONSTRAINT "SPECS_NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."SPECS" ADD CONSTRAINT "SPECS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."SPECS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TYPES_TYPES
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."TYPES_TYPES" ADD CONSTRAINT "TYPES_TYPES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITSTOCK"."TYPES_TYPES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACCESS_GROUPS_METHODS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ACCESS_GROUPS_METHODS" ADD CONSTRAINT "ACCESS_GROUP_FK" FOREIGN KEY ("ACCESS_GROUP_ID")
	  REFERENCES "C##ITSTOCK"."ACCESS_GROUPS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."ACCESS_GROUPS_METHODS" ADD CONSTRAINT "METHOD_FK" FOREIGN KEY ("METHOD_ID")
	  REFERENCES "C##ITSTOCK"."METHODS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADMINS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ADMINS" ADD CONSTRAINT "USER_ACCESS_GROUP_FK" FOREIGN KEY ("ACCESS_GROUP_ID")
	  REFERENCES "C##ITSTOCK"."ACCESS_GROUPS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ITEMS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ITEMS" ADD CONSTRAINT "ITEM_BRAND_FK" FOREIGN KEY ("BRAND_ID")
	  REFERENCES "C##ITSTOCK"."BRANDS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."ITEMS" ADD CONSTRAINT "ITEM_LOCATION_FK" FOREIGN KEY ("LOCATION_ID")
	  REFERENCES "C##ITSTOCK"."LOCATIONS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."ITEMS" ADD CONSTRAINT "ITEM_TYPE_FK" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "C##ITSTOCK"."TYPES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ITEMSPECVALUES
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."ITEMSPECVALUES" ADD CONSTRAINT "ITEMSPECVALUE_ITEM_FK" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "C##ITSTOCK"."ITEMS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."ITEMSPECVALUES" ADD CONSTRAINT "ITEMSPECVALUE_SPEC_FK" FOREIGN KEY ("SPEC_ID")
	  REFERENCES "C##ITSTOCK"."SPECS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECEIPTS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."RECEIPTS" ADD CONSTRAINT "RECEIPT_CLIENT_FK" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "C##ITSTOCK"."CLIENTS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECORDS
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."RECORDS" ADD CONSTRAINT "RECORD_BORROWER_FK" FOREIGN KEY ("CLIENT_BORROWER_ID")
	  REFERENCES "C##ITSTOCK"."CLIENTS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."RECORDS" ADD CONSTRAINT "RECORD_CHECKER_FK" FOREIGN KEY ("ADMIN_CHECKER_ID")
	  REFERENCES "C##ITSTOCK"."ADMINS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."RECORDS" ADD CONSTRAINT "RECORD_RECEIPT_FK" FOREIGN KEY ("RECEIPT_ID")
	  REFERENCES "C##ITSTOCK"."RECEIPTS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."RECORDS" ADD CONSTRAINT "RECORD_RECEIVER_FK" FOREIGN KEY ("ADMIN_RECEIVER_ID")
	  REFERENCES "C##ITSTOCK"."ADMINS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."RECORDS" ADD CONSTRAINT "RECORD_RETURNER_FK" FOREIGN KEY ("CLIENT_RETURNER_ID")
	  REFERENCES "C##ITSTOCK"."CLIENTS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPECS_TYPES
--------------------------------------------------------

  ALTER TABLE "C##ITSTOCK"."SPECS_TYPES" ADD CONSTRAINT "SPEC_FK" FOREIGN KEY ("SPEC_ID")
	  REFERENCES "C##ITSTOCK"."SPECS" ("ID") ENABLE;
  ALTER TABLE "C##ITSTOCK"."SPECS_TYPES" ADD CONSTRAINT "TYPE_FK" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "C##ITSTOCK"."TYPES" ("ID") ENABLE;
